AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Skanny the AI tool to analyze and extract relevant data from PDF's and images

Globals:
  Function:
    Tags:
      version: "v0.0.1"
    Timeout: 60
    MemorySize: 128
    Runtime: !Ref PythonRuntime
    Layers:
      - !Ref SkannyLambdaLayer
    Environment:
      Variables:
        LOG_LEVEL: !Ref LogLevel

Parameters:
  PythonRuntime:
    Type: String
    Default: python3.12
  LogLevel:
    Type: String
    AllowedValues: ["DEBUG", "INFO", "WARNING", "ERROR"]

Resources:
# ------------------------------ project layer ------------------------------
  SkannyLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: src
      CompatibleRuntimes: [!Ref PythonRuntime]
    Metadata:
      BuildMethod: !Ref PythonRuntime
